### ISSUE TITLE
Java conventions

### ISSUE THREAD

**Issue by Maxlego08** [bramar2/armorplusplus#1]
It must not have an uppercase letter for the package name.

[https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html)

**Comment by bramar2** [comment]
It doesn't really affect anything?

**Comment by Maxlego08** [comment]
Of course not, but it is preferable to respect the conventions.

**Comment by bramar2** [comment]
Ok, I'll update version 0.1.3

**Comment by bramar2** [comment]
I re-posted version 0.1.3, and updated the github.
